version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle install
    command: rails db:setup
    command: rails s -p 3000 '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db